= Helloworld


== JOB Jenkins

La définition du JOB Jenkins est réalisée dans le Jenkinsfile.

Le JOB construit une image Docker est publie l'image sur notre dépot : registry.wildwidewest.xyz

Le script Jenkinsfile

* Checkout les sources GIT
* Construit le binaire java de l'application (un jar exécutable springboot)
* Construit l'image Docker de l'application
* Publie l'image Docker sur le registry Docker
* Déploie l'application sur Kubernetes

== Déploiement Kubernetes

Le déploiement de l'application est réalisé en applicant les fichiers de configuration kubernetes

* src/main/kubernetes/postgresql.yml
* src/main/kubernetes/helloworld.yml

=== Deployment

L'objet Deployment spécifie comment déployer un Pod (ensemble de conteneurs Docker).

[source]
----

apiVersion: apps/v1beta1
kind: Deployment <1>
metadata:
  name: postgres <2>
spec:
  replicas: 1 <3>
  template:
    metadata:
     labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres <4>
        ports:
        - containerPort: 5432 <5>
----

<1> Type d'objet Kubernetes
<2> nom de l'application
<3> nombre de replicas
<4> image du conteneur
<5> exposition du port de la base de données

=== Service

L'objet Service fournit un point d'accès aux Pods déployés (par un objet Deployment).

Kubernetes associe notamment une adresse IP au niveau du cluster pour accéder au service.

[source]
----
kind: Service
apiVersion: v1
metadata:
  name: postgres <1>
spec:
  selector:
    app: postgres <2>
  ports:
    - protocol: TCP
      port: 5432 <3>
      targetPort: 5432
----

<1> nom du service
<2> selecteur des pods associés
<3> port d'accès au service

=== Ingress

L'objet Ingress permet de fournir des points d'accès aux services en dehors du cluster.

[source]
----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: helloworld.k8.wildwidewest.xyz <1>
    http:
      paths:
      - backend:
          serviceName: helloworld<2>
          servicePort: 8080<3>
----

<1> Nom DNS de l'application
<2> Nom du service exposé
<3> Port du service exposé

== Remarques

=== Gestion des propriétés

Les propriétés d'une application Kubernetes sont passées en tant que variables d'environnement (pas de fichier de propriétés).

=== DNS

Kubernetes gère un DNS et crée une entrée dans le DNS pour chaque service.

Le service helloworld accède au service "postgres" via le nom du service.