/*
 * This file is generated by jOOQ.
*/
package com.softeam.books.domain;


import com.softeam.books.domain.tables.TBook;
import com.softeam.books.domain.tables.records.TBookRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TBookRecord, Integer> IDENTITY_T_BOOK = Identities0.IDENTITY_T_BOOK;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TBookRecord> T_BOOK_PKEY = UniqueKeys0.T_BOOK_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<TBookRecord, Integer> IDENTITY_T_BOOK = createIdentity(TBook.T_BOOK, TBook.T_BOOK.BOK_ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TBookRecord> T_BOOK_PKEY = createUniqueKey(TBook.T_BOOK, "t_book_pkey", TBook.T_BOOK.BOK_ID);
    }
}
