/*
 * This file is generated by jOOQ.
*/
package com.softeam.books.domain;


import com.softeam.books.domain.tables.TBook;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.t_book</code>.
     */
    public static final TBook T_BOOK = com.softeam.books.domain.tables.TBook.T_BOOK;
}
