/*
 * This file is generated by jOOQ.
*/
package com.softeam.books.domain.tables.records;


import com.softeam.books.domain.tables.TBook;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBookRecord extends UpdatableRecordImpl<TBookRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 440785458;

    /**
     * Setter for <code>public.t_book.bok_id</code>.
     */
    public void setBokId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_book.bok_id</code>.
     */
    public Integer getBokId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.t_book.bok_title</code>.
     */
    public void setBokTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_book.bok_title</code>.
     */
    public String getBokTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_book.bok_authors</code>.
     */
    public void setBokAuthors(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_book.bok_authors</code>.
     */
    public String getBokAuthors() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TBook.T_BOOK.BOK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TBook.T_BOOK.BOK_TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TBook.T_BOOK.BOK_AUTHORS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBokId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBokTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBokAuthors();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBookRecord value1(Integer value) {
        setBokId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBookRecord value2(String value) {
        setBokTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBookRecord value3(String value) {
        setBokAuthors(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBookRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TBookRecord
     */
    public TBookRecord() {
        super(TBook.T_BOOK);
    }

    /**
     * Create a detached, initialised TBookRecord
     */
    public TBookRecord(Integer bokId, String bokTitle, String bokAuthors) {
        super(TBook.T_BOOK);

        set(0, bokId);
        set(1, bokTitle);
        set(2, bokAuthors);
    }
}
