DROP TABLE IF EXISTS T_BOOK;

CREATE SEQUENCE ID_SEQ;

CREATE TABLE T_BOOK (
  BOK_ID  INTEGER      NOT NULL PRIMARY KEY DEFAULT nextval('id_seq'),
  BOK_TITLE    VARCHAR(128) NOT NULL,
  BOK_AUTHORS    VARCHAR(128) NOT NULL
);


INSERT INTO T_BOOK (BOK_ID, BOK_TITLE, BOK_AUTHORS) VALUES (1, 'Design Pattern', 'Erich Gamma, John Vlissides, Ralph Johnson et Richard Helm');

INSERT INTO T_BOOK (BOK_ID, BOK_TITLE, BOK_AUTHORS) VALUES (2, 'Effective Java', 'Joshua Bloch');